http_server:
  address: 0.0.0.0:8000
  read_timeout: 10s
  write_timeout: 10s
  idle_timeout: 60s
  shutdown_timeout: 10s
  max_upload_size_mb: 20
db:
  uri: mongodb://db:27017/database
  migrations_dir: /app/migrations/mongo
photos_dir: /app/photos
