version: '3.8'

services:
  app:
    container_name: comparison_center_app
    build: ./backend/
    env_file:
      - .env
    volumes:
      - ./backend:/app
    ports:
      - ${APP_HOSTPORT}:8000
    depends_on:
      - db
    restart: always

  db:
    container_name: comparison_center_mongo_db
    image: mongo:6.0
    env_file:
      - .env
    volumes:
      - .mongo_db:/data/db
    ports:
      - ${MONGODB_HOSTPORT}:27017
    restart: always

  client:
    container_name: comparison_center_client
    build: ./frontend/
    ports:
      - ${CLIENT_PORT}:3000
    depends_on:
      - app
    restart: always

  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.43.0
    volumes:
      - ./metrics/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    expose:
      - 9090
    restart: always

  node_exporter:
    container_name: node_exporter
    image: prom/node-exporter:v1.5.0
    expose:
      - 9100
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    restart: always

  grafana:
    container_name: grafana
    user: "0:0"
    image: grafana/grafana-oss:9.4.7
    ports:
      - ${GRAFANA_HOSTPORT}:3000
    volumes:
      - ./.grafana_data:/var/lib/grafana
      - ./metrics/grafana/datasources:/etc/grafana/provisioning/datasources
      - ./metrics/grafana/provisioning:/etc/grafana/provisioning/dashboards
    restart: always
