version: '3.8'

services:
  app:
    container_name: comparison_center_app
    build: ./
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - ${APP_HOSTPORT}:8000
    depends_on:
      - db
    restart: always

  db:
    container_name: comparison_center_mongo_db
    image: mongo:6.0
    env_file:
      - .env
    volumes:
      - .mongo_db:/data/db
    ports:
      - ${MONGODB_HOSTPORT}:27017
